apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hsov
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hsov
    app.kubernetes.io/part-of: ci1t-830-0023-app
  name: devfile-sample-hsov
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hsov
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hsov
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0023-tenant/ci1t-830-0023-app/devfile-sample-hsov@sha256:546f9559d8ea04489106de6366cb8c65e4e61af1901f633c6de0172701a11708
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
